version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: go_api
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.template
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/rocket?sslmode=disable
      - REDIS_ADDR=redis:6379
      - S3_ENDPOINT=http://minio:9000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rocket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: minio_s3
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
